#!/usr/bin/env bash
#
# verify-deployment.sh — prove what is running on the SBC matches a commit.
#
#   ./verify-deployment.sh                     on the box: check /opt/sbc
#   ./verify-deployment.sh --remote root@HOST   from a workstation, over ssh
#   ./verify-deployment.sh --repo               from a checkout: does the
#                                               recorded commit still hash the
#                                               way DEPLOYED_COMMIT claims?
#   ./verify-deployment.sh --write <sha>        regenerate DEPLOYED_COMMIT
#
# READ-ONLY in every mode except --write. Run it before touching that box.
#
# WHY THIS EXISTS
# ---------------
# The SBC is deployed by scp, deliberately: a git checkout on a production
# border element means credentials and a .git directory on the one host that
# terminates customer traffic, and that is a worse trade than manual file copy.
#
# The cost of that choice is provenance. Three files copied by hand correspond
# to no commit unless something writes down which one, and the failure mode is
# silent and expensive: the next deploy from a clean checkout of a DIFFERENT
# branch reverts Phase 0 — the ring-aware failover split — and nothing anywhere
# reports that it happened. Calls start walking the gateway ring again and the
# only symptom is a slow rise in INVITE volume toward the carrier.
#
# So DEPLOYED_COMMIT is the record and this script is the check. It is not a
# substitute for version control; it is the smallest thing that makes "what is
# on the box" answerable without putting a repo there.
#
# EXIT CODES
#   0  everything matches
#   1  drift: a file on the box differs from what DEPLOYED_COMMIT records
#   2  cannot check (missing file, unreadable host, bad arguments)

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SBC_DIR="${SBC_DIR:-/opt/sbc}"
STAMP="${STAMP:-$SBC_DIR/DEPLOYED_COMMIT}"
MODE="local"
REMOTE=""
WRITE_SHA=""

# The files that are actually deployed by hand. Adding one here without adding
# it to the deploy is how this check starts lying, so keep the two together.
TRACKED=(render.sh asterisk/extensions.conf.tpl didctl.sh)

B=$'\033[1m'; R=$'\033[31m'; G=$'\033[32m'; Y=$'\033[33m'; D=$'\033[2m'; N=$'\033[0m'
[[ -t 1 ]] || { B=""; R=""; G=""; Y=""; D=""; N=""; }

die()  { echo "verify-deployment.sh: ERROR: $*" >&2; exit 2; }
info() { echo "  $*"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --remote) MODE="remote"; REMOTE="$2"; shift 2 ;;
    --repo)   MODE="repo"; shift ;;
    --write)  MODE="write"; WRITE_SHA="$2"; shift 2 ;;
    --stamp)  STAMP="$2"; shift 2 ;;
    --dir)    SBC_DIR="$2"; shift 2 ;;
    -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
    *) die "unknown argument '$1'" ;;
  esac
done

sha_of() { sha256sum "$1" 2>/dev/null | cut -d' ' -f1; }

# ---------------------------------------------------------------------------
# --write : regenerate the stamp from a commit in this checkout
# ---------------------------------------------------------------------------
if [[ "$MODE" == "write" ]]; then
  command -v git >/dev/null || die "--write needs git"
  git -C "$HERE" rev-parse --verify "$WRITE_SHA^{commit}" >/dev/null 2>&1 \
    || die "'$WRITE_SHA' is not a commit in this repo"
  FULL="$(git -C "$HERE" rev-parse "$WRITE_SHA^{commit}")"
  DIRTY=""
  [[ -n "$(git -C "$HERE" status --porcelain)" ]] && DIRTY=" (WORKING TREE DIRTY AT WRITE TIME)"

  {
    echo "# /opt/sbc provenance. Generated by verify-deployment.sh --write."
    echo "# Check with: ./verify-deployment.sh   (read-only)"
    echo "#"
    echo "# The box is deployed by scp, not by checkout: no .git and no"
    echo "# credentials on a production border element. This file is what makes"
    echo "# 'which commit is running' answerable anyway."
    echo "commit=$FULL$DIRTY"
    echo "deployed_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "deployed_by=verify-deployment.sh --write"
    echo "host=${DEPLOY_HOST:-167.235.206.206}"
    echo "#"
    echo "# file sha256 (as deployed)"
    for f in "${TRACKED[@]}"; do
      printf 'file=%s %s\n' "$f" "$(git -C "$HERE" show "$FULL:$f" | sha256sum | cut -d' ' -f1)"
    done
    echo "#"
    echo "# --- STATE OF THIS DEPLOY -------------------------------------------"
    echo "# LIVE: Phase 0 (ring-aware CHANUNAVAIL split, MAX_ROUTE_ATTEMPTS=2),"
    echo "#       DID pool reallocation (70 moves), 3 suppressed incumbents."
    echo "# NOT LIVE: Phase 1 in any form."
    echo "#"
    echo "# UNEXECUTED ACCEPTANCE CRITERIA: 24, 25, 26"
    echo "#   These cover the Phase 0 failover split and have NEVER been run --"
    echo "#   there has been no Asterisk+SIPp box to run them on. Phase 0 is live"
    echo "#   and carries real calls the moment the trunk returns, so running"
    echo "#   them is the FIRST thing the lab box does: before VERIFY item V3"
    echo "#   and before any Phase 1 work. V3 only gates code that has not"
    echo "#   shipped; criteria 24-26 gate code that has."
    echo "unexecuted_criteria=24,25,26"
  }
  echo "  wrote stamp for $FULL$DIRTY"
  exit 0
fi

# ---------------------------------------------------------------------------
# Read the stamp (locally, or off the box)
# ---------------------------------------------------------------------------
read_stamp() {
  case "$MODE" in
    remote) ssh -o BatchMode=yes -o ConnectTimeout=10 "$REMOTE" "cat '$STAMP'" 2>/dev/null ;;
    *)      cat "$STAMP" 2>/dev/null ;;
  esac
}

STAMP_TXT="$(read_stamp)"
[[ -n "$STAMP_TXT" ]] || die "cannot read $STAMP${REMOTE:+ on $REMOTE}
       The box has no provenance record. Do NOT deploy over it blind:
       regenerate one with --write against the commit you believe is running,
       and confirm the hashes match before trusting it."

COMMIT="$(sed -n 's/^commit=//p' <<< "$STAMP_TXT" | head -1)"
WHEN="$(sed -n 's/^deployed_at=//p' <<< "$STAMP_TXT" | head -1)"
UNEXEC="$(sed -n 's/^unexecuted_criteria=//p' <<< "$STAMP_TXT" | head -1)"

echo
echo "${B}deployment check${N}   ${REMOTE:-$SBC_DIR}"
echo "  commit      ${COMMIT:-<none recorded>}"
echo "  deployed    ${WHEN:-<unknown>}"
echo

# ---------------------------------------------------------------------------
# --repo : does this checkout still produce the hashes the stamp claims?
# Catches a rewritten branch or a tag moved out from under the record.
# ---------------------------------------------------------------------------
if [[ "$MODE" == "repo" ]]; then
  command -v git >/dev/null || die "--repo needs git"
  git -C "$HERE" rev-parse --verify "${COMMIT%% *}^{commit}" >/dev/null 2>&1 \
    || die "commit ${COMMIT%% *} is not in this repo. The box is running something
       this checkout cannot account for."
  bad=0
  while read -r f want; do
    got="$(git -C "$HERE" show "${COMMIT%% *}:$f" 2>/dev/null | sha256sum | cut -d' ' -f1)"
    if [[ "$got" == "$want" ]]; then
      printf '  %sOK%s    %-32s %s\n' "$G" "$N" "$f" "${want:0:12}"
    else
      printf '  %sDRIFT%s %-32s repo=%s stamp=%s\n' "$R" "$N" "$f" "${got:0:12}" "${want:0:12}"
      bad=1
    fi
  done < <(sed -n 's/^file=//p' <<< "$STAMP_TXT")
  echo
  (( bad )) && { echo "  ${R}The recorded commit no longer hashes as recorded.${N}"; exit 1; }
  echo "  ${G}Repo agrees with the stamp.${N}"
  exit 0
fi

# ---------------------------------------------------------------------------
# local / remote : hash what is actually on the box
# ---------------------------------------------------------------------------
box_sha() {
  case "$MODE" in
    remote) ssh -o BatchMode=yes -o ConnectTimeout=10 "$REMOTE" \
              "sha256sum '$SBC_DIR/$1' 2>/dev/null | cut -d' ' -f1" 2>/dev/null ;;
    *)      sha_of "$SBC_DIR/$1" ;;
  esac
}

bad=0; missing=0
while read -r f want; do
  got="$(box_sha "$f")"
  if [[ -z "$got" ]]; then
    printf '  %sMISSING%s %-30s not present on the box\n' "$R" "$N" "$f"
    missing=1; bad=1
  elif [[ "$got" == "$want" ]]; then
    printf '  %sOK%s      %-30s %s\n' "$G" "$N" "$f" "${want:0:12}"
  else
    printf '  %sDRIFT%s   %-30s box=%s stamp=%s\n' "$R" "$N" "$f" "${got:0:12}" "${want:0:12}"
    bad=1
  fi
done < <(sed -n 's/^file=//p' <<< "$STAMP_TXT")

echo
if [[ -n "$UNEXEC" ]]; then
  echo "  ${Y}Acceptance criteria never executed against this build: $UNEXEC${N}"
  echo "  ${D}Run these before anything else on the lab box. They gate code that${N}"
  echo "  ${D}is already carrying calls, which outranks gating code that is not.${N}"
  echo
fi

if (( bad )); then
  echo "  ${R}${B}DRIFT.${N} The box is not running the recorded commit."
  echo "  Reconcile before deploying: a deploy from a clean checkout will"
  echo "  silently revert whatever the box has that the commit does not."
  exit 1
fi

echo "  ${G}${B}Match.${N} The box is running ${COMMIT%% *}."
exit 0
