#!/usr/bin/env bash
#
# capture-acceptance.sh — run the acceptance evidence and emit a REDACTED
# markdown block to paste into RUNBOOK.md.
#
#   sudo ./tests/capture-acceptance.sh
#
# Writes RUNBOOK-acceptance.generated.md at the repo root (gitignored).
#
# Redaction is BEST EFFORT and you must read the output before pasting it
# into a file you are going to commit. Known and configured values are
# replaced with tokens; anything else that looks like a public IPv4 address,
# a SIP Call-ID or a NANP phone number is replaced generically. It will not
# catch a secret in a format it has never seen.
#
# What gets replaced:
#   SBC_PUBLIC_IP        -> <SBC_IP>
#   PK_CLIENT_IP_1/2     -> <PK_IP_1> / <PK_IP_2>
#   FRACTEL_PROXY_IPS    -> <FRACTEL_IP_1..N>
#   ADMIN_SSH_IP         -> <ADMIN_IP>
#   any other non-loopback IPv4 -> <IP>
#   Call-ID values       -> <CALL_ID>
#   10/11-digit NANP numbers -> <NUMBER>

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
PROD_CONF="${PROD_CONF:-$ROOT/config.env}"
OUT="$ROOT/RUNBOOK-acceptance.generated.md"

[[ "$(id -u)" -eq 0 ]] || { echo "must run as root"; exit 1; }

# ---------------------------------------------------------------------------
# Build the redaction filter from whatever config.env actually contains.
# ---------------------------------------------------------------------------
SED_ARGS=()
if [[ -f "$PROD_CONF" ]]; then
  # shellcheck disable=SC1090
  ( set -a; source "$PROD_CONF"; set +a )
  # shellcheck disable=SC1090
  set -a; source "$PROD_CONF"; set +a

  esc() { printf '%s' "$1" | sed 's/\./\\./g'; }

  [[ -n "${SBC_PUBLIC_IP:-}"  ]] && SED_ARGS+=(-e "s/$(esc "$SBC_PUBLIC_IP")/<SBC_IP>/g")
  [[ -n "${PK_CLIENT_IP_1:-}" ]] && SED_ARGS+=(-e "s/$(esc "$PK_CLIENT_IP_1")/<PK_IP_1>/g")
  [[ -n "${PK_CLIENT_IP_2:-}" ]] && SED_ARGS+=(-e "s/$(esc "$PK_CLIENT_IP_2")/<PK_IP_2>/g")

  n=0
  IFS=',' read -r -a _fp <<< "${FRACTEL_PROXY_IPS:-}"
  for f in "${_fp[@]}"; do
    f="$(echo "${f%%:*}" | tr -d '[:space:]')"; [[ -n "$f" ]] || continue
    n=$((n+1)); SED_ARGS+=(-e "s/$(esc "$f")/<FRACTEL_IP_$n>/g")
  done

  IFS=',' read -r -a _ad <<< "${ADMIN_SSH_IP:-}"
  for a in "${_ad[@]}"; do
    a="$(echo "${a%%/*}" | tr -d '[:space:]')"; [[ -n "$a" ]] || continue
    SED_ARGS+=(-e "s/$(esc "$a")/<ADMIN_IP>/g")
  done
fi

# Generic sweeps, applied after the specific ones.
SED_ARGS+=(
  # Any remaining IPv4 that is not loopback.
  -E
  -e 's/\b(([0-9]{1,3}\.){3}[0-9]{1,3})\b/<IP>/g'
  -e 's/<IP>/<IP>/g'
  # SIP Call-ID header values and bare call-id-looking tokens.
  -e 's/(Call-ID:[[:space:]]*)[^[:space:]]+/\1<CALL_ID>/gI'
  -e 's/(call[_-]?id=)[^[:space:]",]+/\1<CALL_ID>/gI'
  # NANP numbers.
  -e 's/\b1?[2-9][0-9]{9}\b/<NUMBER>/g'
)

redact() {
  # Restore loopback addresses after the blanket IPv4 sweep — they carry no
  # information and blanking them makes the output unreadable.
  sed "${SED_ARGS[@]}" | sed -E 's/<IP>\.([0-9]+) > <IP>\./<IP>.\1 > <IP>./g'
}

emit() { # emit <heading> <command...>
  local title="$1"; shift
  {
    echo
    echo "### $title"
    echo
    echo '```'
    echo "\$ $*"
    "$@" 2>&1 | redact
    echo '```'
  } >> "$OUT"
}

# ---------------------------------------------------------------------------
: > "$OUT"
{
  echo "<!-- Generated by tests/capture-acceptance.sh on $(date -u '+%F %T UTC') -->"
  echo "<!-- REDACTED, BUT READ IT BEFORE COMMITTING. Redaction is best effort. -->"
  echo
  echo "## Acceptance evidence"
  echo
  echo "Host: \`$(. /etc/os-release 2>/dev/null; echo "${PRETTY_NAME:-unknown}")\`  "
  echo "Asterisk: \`$(asterisk -V 2>/dev/null)\`  "
  echo "Captured: \`$(date -u '+%F %T UTC')\`"
} >> "$OUT"

echo "Collecting configuration evidence..."
emit "Criterion 1 — endpoints and gateway reachability" \
     asterisk -rx "pjsip show endpoints"
emit "Criterion 1 — gateway contacts (qualify status)" \
     asterisk -rx "pjsip show contacts"
emit "Criterion 1 — IP identification (which source maps to which endpoint)" \
     asterisk -rx "pjsip show identifies"
emit "Criterion 10 — direct_media is off on the customer leg" \
     bash -c "asterisk -rx 'pjsip show endpoint pkclient1' | grep -iE 'direct_media|rtp_symmetric|force_rport'"
emit "Criterion 10 — direct_media is off on the carrier leg" \
     bash -c "asterisk -rx 'pjsip show endpoint fractel1' | grep -iE 'direct_media|rtp_symmetric|force_rport'"
emit "Criterion 12 — the carrier leg asserts our DID, not the customer's" \
     bash -c "asterisk -rx 'pjsip show endpoint fractel1' | grep -iE 'send_pai|send_rpid|send_diversion|trust_id_outbound|trust_id_inbound'"
emit "Criteria 13/14/15 — DID pools loaded into the running dialplan" \
     bash -c "$ROOT/didctl.sh pools"
emit "Criterion 13 — per-DID distribution and cap compliance, from the CDR alone" \
     bash -c "$ROOT/didctl.sh distribution"
emit "Criterion 14 — per-DID daily cap and today's usage" \
     bash -c "$ROOT/didctl.sh status"
emit "Criterion 16 — high-cost prefixes loaded" \
     bash -c "asterisk -rx 'dialplan show sbc-lrn-blocklist' | tail -3"
emit "Dialplan functions the DID logic depends on" \
     bash -c "for f in LOCK TRYLOCK UNLOCK DB DIALPLAN_EXISTS; do printf '%-16s ' \$f; asterisk -rx \"core show function \$f\" >/dev/null 2>&1 && echo present || echo MISSING; done"
emit "Firewall ruleset (layer 1)" \
     bash -c "nft list table inet sbc 2>/dev/null || echo 'NOT LOADED'"
emit "Boot persistence — unit states" \
     systemctl is-enabled asterisk nftables sbc-healthcheck.timer sbc-killswitch.service
emit "Health check" \
     bash -c "$ROOT/healthcheck.sh; echo \"exit=\$?\""
emit "Killswitch status" \
     bash -c "$ROOT/killswitch.sh status; echo \"exit=\$?\""

echo "Running the acceptance suite (this takes a couple of minutes)..."
{
  echo
  echo "### Criteria 1-11 — acceptance suite"
  echo
  echo '```'
  echo "\$ sudo ./tests/run-acceptance.sh"
} >> "$OUT"
"$HERE/run-acceptance.sh" 2>&1 | sed -E 's/\x1b\[[0-9;]*m//g' | redact >> "$OUT"
SUITE_RC=$?
{
  echo '```'
  echo
  echo "Suite exit code: \`$SUITE_RC\` (0 = no failures)"
  echo
  echo "> Criteria 3b (host firewall) and 11 (reboot) report SKIP. They cannot be"
  echo "> proven from on-box and must be done by hand — see RUNBOOK.md."
  echo ">"
  echo "> Criterion 12 was checked against a SIPp stub. It proves the INVITE"
  echo "> leaving this box carries our DID in all three identity headers and none"
  echo "> of the customer's value. It does NOT prove what FracTEL attests off, or"
  echo "> that they accept these numbers as caller ID on this subaccount. Both"
  echo "> need the live trunk — RUNBOOK.md section 6."
} >> "$OUT"

echo
echo "Written: $OUT"
echo
echo "  1. READ IT. Redaction is best effort, not a guarantee."
echo "  2. Paste it into the acceptance section of RUNBOOK.md."
echo "  3. This generated file is gitignored — do not commit it directly."
echo
