; ===========================================================================
; extensions.conf — rendered by render.sh from @@RENDERED_FROM@@.
;
; This file is the fraud stop. Read it before you change it.
;
; The customer context has exactly ONE egress: Dial(PJSIP/<n>@fractelN).
; There are no context includes, no Local/ channels, no AGI, no System(), no
; Originate(). res_agi, app_system, func_shell and app_originate are not even
; loaded (see modules.conf). If traffic from any customer address
; (@@PK_CLIENT_IP_CSV@@) can reach anything other than the FracTEL trunk, that
; is a bug and it is the expensive kind.
;
; Order of checks, cheapest and most consequential first:
;
;   1. killswitch      operator has pulled the plug
;   2. destination     NANP allowlist + high-risk NPA denylist
;   3. LRN blocklist   high-cost prefixes from the carrier rate deck
;   4. caller ID       ADVISORY ONLY — logged, never trusted, always replaced
;   5. CPS             protects the FracTEL trunk from a dialer blast
;   6. concurrency     per customer IP
;   7. DID selection   NPA pool -> overflow, with a per-DID daily cap
;   8. caller ID SET   From / PAI / RPID all forced to the selected DID
;   9. dial            FracTEL, round-robin, failover capped at
;                      SBC_MAX_ATTEMPTS INVITEs and refused after ringing
;
; Destination is checked before the concurrency slot is taken, so a burst of
; junk destinations cannot starve legitimate traffic out of the cap. DID
; selection happens AFTER the CPS and concurrency checks, so a throttled call
; never burns a number's daily allowance.
;
; ---------------------------------------------------------------------------
; THE SBC ASSIGNS CALLER ID. The customer's value is discarded on every call.
;
; This reverses the original design. A customer's ViciDial put 50,864 calls on
; one DID in an afternoon and tripped a carrier fraud alert: it matched caller
; ID to destination area code and silently fell back to a single default
; number when no match existed. Caller ID is no longer theirs to get wrong.
;
; Three things have to hold, and each is checked here rather than assumed:
;
;   - From, P-Asserted-Identity and Remote-Party-ID all carry the DID this box
;     selected. FracTEL most likely attests off From, but a leak in any one of
;     the three could key attestation to the wrong number. PAI and RPID are
;     generated by res_pjsip from CALLERID(num) — see send_pai / send_rpid on
;     the fractel endpoints in pjsip.conf.
;   - No path exists that dials with a customer-supplied CID. If the selected
;     DID is empty or malformed the call is REFUSED with 503 and an ERROR is
;     logged. There is no fallback to what the customer sent.
;   - No path exists that dials without consuming a DID's daily allowance.
;     The cap is enforced here, in the call path, not in a report the next
;     morning.
; ---------------------------------------------------------------------------
;
; Every rejection emits a NOTICE of the form
;     SBC-REJECT reason=<REASON> ...
; which is what monitor.sh counts and what the acceptance suite greps for.
; ===========================================================================

[general]
static=yes
; No 'dialplan save' from the CLI. The file on disk is the only source of
; truth, and it is generated from config.env.
writeprotect=yes
autofallthrough=yes
; Runtime globals (the killswitch) must survive a 'dialplan reload'.
; This protects ONLY globals never declared below in [globals] - verified
; live 2026-08-29 (see RUNBOOK.md): SBC_KILLSWITCH, set at runtime and
; absent from [globals] by design, survives a plain reload unchanged.
; Anything that IS declared below (SBC_MAX_CPS, SBC_MAX_CONCURRENT, every
; limit in this file) gets silently overwritten back to ITS value on
; every reload regardless of clearglobalvars - a runtime override to any
; of those does not survive a reload, warning or no warning either way.
clearglobalvars=no


[globals]
SBC_MAX_CONCURRENT=@@MAX_CONCURRENT_PER_IP@@
SBC_MAX_CPS=@@MAX_CPS@@
SBC_NANP_ONLY=@@NANP_ONLY@@
SBC_BLOCK_NPA=@@BLOCK_HIGH_RISK_NPA@@
SBC_BLOCK_976=@@BLOCK_976@@
SBC_BLOCKED_NPAS=@@SBC_BLOCKED_NPAS@@
SBC_VALIDATE_CID=@@VALIDATE_CALLERID@@
SBC_NORMALIZE_CID=@@NORMALIZE_CALLERID@@
SBC_DIAL_TIMEOUT=@@DIAL_TIMEOUT@@
SBC_GW_COUNT=@@FRACTEL_GW_COUNT@@
; Total INVITEs toward the carrier per customer call, first attempt included.
; render.sh has already clamped this to min(MAX_ROUTE_ATTEMPTS, gateway count),
; so the dialplan has exactly one bound to check.
SBC_MAX_ATTEMPTS=@@SBC_MAX_ATTEMPTS@@
; Below this many milliseconds, a failure that never rang is the trunk saying
; no rather than a person saying no. See the failover block in [sbc-customer].
SBC_FAST_REJECT_MS=@@FAST_REJECT_MS@@
SBC_DID_CAP=@@DID_DAILY_CAP@@
SBC_XFER_ON=@@TRANSFER_DETECT@@
SBC_XFER_TF_NPAS=@@SBC_TF_NPAS@@
SBC_XFER_MIN_CALLS=@@TRANSFER_MIN_CALLS@@
SBC_XFER_MIN_ACD=@@TRANSFER_MIN_ACD@@
@@INCLUDE:fractel_globals@@

; --- DID pools, generated from dids.csv ------------------------------------
; One SBC_DID_POOL_<npa> / SBC_DID_CNT_<npa> pair per destination area code,
; plus SBC_DID_POOL_OVERFLOW. Pipe-delimited, because a comma is the argument
; separator in every dialplan application and CUT() would need it escaped.
;
; The dialplan reads ${GLOBAL(SBC_DID_POOL_${SBC_NPA})}, so an NPA with no
; pool of its own yields an empty string and falls straight to OVERFLOW.
;
; @@DID_TOTAL@@ number(s) across @@DID_NPA_POOLS@@ NPA pool(s), plus
; @@OVERFLOW_COUNT@@ in overflow. Daily cap @@DID_DAILY_CAP@@ per DID.
@@INCLUDE:did_globals@@

; SBC_KILLSWITCH is deliberately NOT declared here. killswitch.sh sets it at
; runtime with `dialplan set global`. If it were declared, a `dialplan reload`
; would silently reset it to 0 and quietly restore customer traffic while the
; operator believed the plug was still pulled. Unset is treated as off.
;
; SBC_GW_ROT and SBC_ROT_<pool> are not declared here either, for a different
; reason: they are the rotation counters and they are written at runtime with
; Set(GLOBAL(...)). Declaring them would be harmless but misleading — their
; value is never configuration.
;
; Those rotors live in memory, not in the Asterisk database, and that is
; deliberate. Rotation only has to spread load; it does not have to survive a
; restart, and making it durable would put an sqlite write in the path of
; every single call for no benefit. What DOES have to survive a restart is the
; per-DID daily counter, and that is the one thing kept in AstDB.
;
; They are also not derived from ${UNIQUEID}. The uniqueid sequence increments
; per CHANNEL, not per call, and an answered call allocates two of them (the
; customer leg and the outbound leg toward FracTEL). Sequence numbers on the
; customer leg therefore advance by two in steady state, so `seq % 6` yields
; only three distinct residues and three of the six gateways would never be
; used. The same trap applies to any even-sized DID pool. A rotor incremented
; once per call is correct for every divisor.


; ===========================================================================
; [default] — nothing should ever land here. Defined explicitly and left
; hostile so that an endpoint accidentally rendered without a context= line
; cannot fall through into something permissive.
; ===========================================================================
; Patterns are enumerated rather than using a bare '_.', which would also
; match the special extensions h/i/t and shadow them. Anything not matched
; here gets a 404 straight from extension matching, which is still a refusal
; — just one that logs less.
[default]
exten => h,1,NoOp(default teardown)
exten => _X.,1,Goto(refuse,1)
exten => _[+*#].,1,Goto(refuse,1)
exten => _[a-zA-Z].,1,Goto(refuse,1)
exten => refuse,1,Log(WARNING,SBC-REJECT reason=LANDED_IN_DEFAULT_CONTEXT exten=${EXTEN} src=${CHANNEL(pjsip,remote_addr)})
 same => n,Hangup(21)


; ===========================================================================
; [sbc-fractel-inbound] — the carrier's context.
;
; This is an outbound-only trunk. An INVITE arriving from FracTEL is either a
; misconfiguration on their side or someone spoofing their address, and either
; way it does not get dialplan. In-dialog requests on an established call
; (re-INVITE, BYE, in-dialog OPTIONS) are matched to the existing dialog by
; the transaction layer and never reach here, so answered calls tear down
; normally.
; ===========================================================================
[sbc-fractel-inbound]
exten => h,1,NoOp(fractel leg teardown cause=${HANGUPCAUSE})
exten => _X.,1,Goto(refuse,1)
exten => _[+*#].,1,Goto(refuse,1)
exten => _[a-zA-Z].,1,Goto(refuse,1)
exten => refuse,1,Log(NOTICE,SBC-REJECT reason=INBOUND_FROM_CARRIER exten=${EXTEN} src=${CHANNEL(pjsip,remote_addr)} callid=${CHANNEL(pjsip,call-id)})
 same => n,Hangup(21)


; ===========================================================================
; [sbc-customer] — the only context reachable from customer traffic.
; ===========================================================================
[sbc-customer]

; --- E.164 alias. A dialer sending +1NXXNXXXXXX enters here, gets stripped to
; --- digits, and re-enters the main pattern below.
exten => _+X.,1,Set(SBC_D=${FILTER(0-9,${EXTEN})})
 same => n,Goto(sbc-customer,${SBC_D},1)

; --- Main entry point ------------------------------------------------------
exten => _X.,1,NoOp(SBC inbound raw=${EXTEN} cid=${CALLERID(num)} ep=${CHANNEL(endpoint)})

 ; Capture identity up front. These are the fields handed over on a traceback
 ; request, so they are recorded before any check can reject the call — a
 ; rejected call still produces a CDR row (cdr.conf sets unanswered=yes).
 same => n,Set(SBC_RADDR=${CHANNEL(pjsip,remote_addr)})
 same => n,Set(__SBC_SRC_IP=${CUT(SBC_RADDR,:,1)})
 same => n,Set(__SBC_EP=${CHANNEL(endpoint)})
 same => n,Set(__SBC_CALLID=${CHANNEL(pjsip,call-id)})
 same => n,Set(__SBC_CID_RAW=${CALLERID(num)})
 same => n,Set(CDR(source_ip)=${SBC_SRC_IP})
 same => n,Set(CDR(customer_endpoint)=${SBC_EP})
 same => n,Set(CDR(sip_call_id)=${SBC_CALLID})
 same => n,Set(CDR(caller_id)=${SBC_CID_RAW})
 same => n,Set(CDR(destination)=${EXTEN})
 same => n,Set(CDR(reject_reason)=)
 same => n,Set(CDR(fractel_gateway_used)=)

 ; ---- 1. killswitch ------------------------------------------------------
 same => n,GotoIf($["${SBC_KILLSWITCH}" = "1"]?rej_killswitch)

 ; ---- 2. destination -----------------------------------------------------
 same => n,Set(SBC_DEST=${FILTER(0-9,${EXTEN})})
 same => n,GotoIf($[${LEN(${SBC_DEST})} = 0]?rej_dest)
 same => n,GotoIf($["${SBC_NANP_ONLY}" != "true"]?dest_ok)

 ; Normalise to 11 digits. _NXXNXXXXXX gets a 1 prepended; _1NXXNXXXXXX is
 ; already there; anything else is not NANP and is refused.
 same => n,GotoIf($[${LEN(${SBC_DEST})} = 10]?dest_add1)
 same => n,GotoIf($[${LEN(${SBC_DEST})} = 11]?dest_chk)
 same => n,Goto(rej_dest)
 same => n(dest_add1),Set(SBC_DEST=1${SBC_DEST})

 same => n(dest_chk),GotoIf($["${SBC_DEST:0:1}" != "1"]?rej_dest)
 same => n,Set(SBC_NPA=${SBC_DEST:1:3})
 same => n,Set(SBC_NXX=${SBC_DEST:4:3})
 ; NPA and NXX must both begin 2-9 (the N in _1NXXNXXXXXX).
 same => n,GotoIf($[${SBC_NPA:0:1} < 2]?rej_dest)
 same => n,GotoIf($[${SBC_NXX:0:1} < 2]?rej_dest)
 ; N11 service codes (211/311/411/511/611/711/811/911) are never valid NPAs.
 same => n,GotoIf($["${SBC_NPA:1:2}" = "11"]?rej_dest)

 ; 976 is US domestic premium-rate.
 same => n,GotoIf($["${SBC_BLOCK_976}" != "true"]?dest_npa)
 same => n,GotoIf($["${SBC_NXX}" = "976"]?rej_npa)

 ; High-risk NANP area codes. NANP-only is NOT enough on its own: the whole
 ; Caribbean is inside the NANP and matches _1NXXNXXXXXX perfectly while
 ; costing dollars a minute. +1-876, +1-809/829/849, +1-284 and friends are
 ; the classic IRSF destinations. Membership test against a comma-wrapped
 ; list, so ",876," matches only the whole area code.
 same => n(dest_npa),GotoIf($["${SBC_BLOCK_NPA}" != "true"]?dest_ok)
 same => n,GotoIf($["${SBC_BLOCKED_NPAS}" : ".*,${SBC_NPA},"]?rej_npa)

 same => n(dest_ok),Set(CDR(destination)=${SBC_DEST})
 ; SBC_NPA is set during NANP normalisation above — but that whole block is
 ; skipped when SBC_NANP_ONLY is false, and an unset NPA would make
 ; ${GLOBAL(SBC_DID_POOL_${SBC_NPA})} resolve to SBC_DID_POOL_ (empty) and
 ; send EVERY call to overflow without anything looking wrong. Derive it here
 ; if the allowlist did not.
 ;
 ; With the allowlist off and a genuinely non-NANP destination this yields a
 ; nonsense NPA, no pool matches, and the call takes an overflow DID and logs
 ; WARN. That is the correct outcome: it still asserts a number we own and it
 ; still obeys the daily cap.
 same => n,ExecIf($["${SBC_NPA}" = ""]?Set(SBC_NPA=${SBC_DEST:1:3}))
 same => n,Set(CDR(destination_npa)=${SBC_NPA})

 ; ---- 3. high-cost LRN prefix blocklist ----------------------------------
 ; [sbc-lrn-blocklist] is generated from blocklist.csv, one extension per
 ; prefix. Asterisk's extension matcher already prefers the most specific
 ; pattern, so longest-prefix-wins comes for free and the whole test is one
 ; hash lookup — 1,248 prefixes cost the same per INVITE as 12. A linear
 ; scan over a joined string would be O(rows) on every call.
 ;
 ; The Gosub sets SBC_LRN_PREFIX / _RATE / _DEST on a hit and is guarded by
 ; DIALPLAN_EXISTS, so on the overwhelmingly common miss nothing runs at all.
 same => n,Set(SBC_LRN_PREFIX=)
 same => n,GotoIf($[${DIALPLAN_EXISTS(sbc-lrn-blocklist,${SBC_DEST},1)} = 0]?lrn_ok)
 same => n,Gosub(sbc-lrn-blocklist,${SBC_DEST},1)
 same => n,GotoIf($["${SBC_LRN_PREFIX}" != ""]?rej_lrn)
 same => n(lrn_ok),NoOp(destination is not in the high-cost blocklist)

 ; ---- 4. caller ID — ADVISORY ONLY ---------------------------------------
 ; Whatever the customer sent is discarded further down and replaced with the
 ; DID this box selects. Refusing the call over a field we never use would
 ; throw away revenue for nothing, so by default a malformed CID is LOGGED at
 ; WARNING and the call proceeds.
 ;
 ; The signal still matters: a dialer that starts emitting blanks or garbage
 ; is telling you something has broken on the customer's side, and it is
 ; cheaper to hear about it here than in a traceback. SBC_VALIDATE_CID=true
 ; restores the old behaviour and refuses the call with 403.
 ;
 ; The raw value stays in CDR(caller_id) and is set at the top of this
 ; extension, before any check can reject the call.
 same => n,Set(SBC_CIDN=${FILTER(0-9,${SBC_CID_RAW})})
 same => n,Set(SBC_CID_OK=1)
 same => n,GotoIf($[${LEN(${SBC_CIDN})} = 10]?cid_add1)
 same => n,GotoIf($[${LEN(${SBC_CIDN})} = 11]?cid_chk)
 ; Empty, alphabetic or the wrong length. Nothing below can safely index it.
 same => n,Set(SBC_CID_OK=0)
 same => n,Goto(cid_verdict)
 same => n(cid_add1),Set(SBC_CIDN=1${SBC_CIDN})
 same => n(cid_chk),ExecIf($["${SBC_CIDN:0:1}" != "1"]?Set(SBC_CID_OK=0))
 same => n,ExecIf($[${SBC_CIDN:1:1} < 2]?Set(SBC_CID_OK=0))
 same => n,ExecIf($[${SBC_CIDN:4:1} < 2]?Set(SBC_CID_OK=0))
 ; Caller ID identical to the number being dialled is a dialer bug or a
 ; spoofing attempt. Either way it is not a real originating number.
 same => n,ExecIf($["${SBC_CIDN}" = "${SBC_DEST}"]?Set(SBC_CID_OK=0))
 same => n(cid_verdict),GotoIf($["${SBC_CID_OK}" = "1"]?cid_done)
 same => n,Log(WARNING,SBC-CID-INVALID callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} custcid=${SBC_CID_RAW} dst=${SBC_DEST} note=discarded-and-replaced)
 same => n,GotoIf($["${SBC_VALIDATE_CID}" = "true"]?rej_cid)
 same => n(cid_done),NoOp(customer cid=${SBC_CID_RAW} valid=${SBC_CID_OK} discarded=yes)

 ; ---- 4. CPS -------------------------------------------------------------
 ; The group name is the current epoch second, so GROUP_COUNT returns the
 ; number of calls that started during this second and are still up — which
 ; at the moment of the check is every call that started this second.
 ; Counted across both customer IPs combined: FracTEL's fraud system reacts
 ; to the aggregate arriving from our one source address, not per-endpoint.
 ; EPOCH is read ONCE into a variable. Reading it twice risks the second read
 ; landing in the next second, which would count a group this channel is not
 ; in and let an extra call through at every second boundary.
 same => n,Set(SBC_SEC=${EPOCH})
 same => n,Set(GROUP(cps)=${SBC_SEC})
 same => n,Set(SBC_CPSNOW=${GROUP_COUNT(${SBC_SEC}@cps)})
 same => n,GotoIf($[${SBC_CPSNOW} > ${SBC_MAX_CPS}]?rej_cps)

 ; ---- 5. concurrency, per customer endpoint (so per customer IP) ---------
 ; GROUP_COUNT includes this channel, so with a cap of 3 the fourth
 ; simultaneous call sees 4 and is refused.
 same => n,Set(GROUP(cust)=${SBC_EP})
 same => n,Set(SBC_CCNOW=${GROUP_COUNT(${SBC_EP}@cust)})
 same => n,GotoIf($[${SBC_CCNOW} > ${SBC_MAX_CONCURRENT}]?rej_cap)

 ; ---- 7. transfer-leg detection ------------------------------------------
 ; A transfer leg is an agent bridging a live prospect to the US buyer. The
 ; buyer has to see the PROSPECT's number — it is their callback path and
 ; their CRM record — and ViciDial already sets it correctly on those legs.
 ; Rewriting it would show the buyer a stranger.
 ;
 ; Detection is on the DESTINATION and never on caller ID. The customer sends
 ; arbitrary caller ID on every call, which is the entire reason this SBC
 ; exists; a caller-ID-based rule would be defeated by exactly the
 ; misconfiguration it has to survive.
 ;
 ; This runs after the destination checks, so the NANP allowlist, the NPA
 ; denylist and the high-cost blocklist have already had their say. A transfer
 ; leg is not a trusted call — it is a call whose caller ID we do not own.
 same => n,Set(SBC_DAY=${STRFTIME(${EPOCH},,%Y%m%d)})
 same => n,Set(SBC_XFER=)
 same => n,GotoIf($["${SBC_XFER_ON}" != "true"]?xfer_no)

 ; --- rule 1: toll-free destination ---------------------------------------
 ; Stateless and immediate, and it runs before any database read. Consumer
 ; prospects are never toll-free.
 same => n,GotoIf($["${SBC_XFER_TF_NPAS}" : ".*,${SBC_NPA},"]?xfer_tollfree)

 ; --- rule 2: learned destination -----------------------------------------
 ; ONE database read, and only ever a read. The counters behind it are
 ; written in the hangup handler at the bottom of this context, so learning
 ; can never add post-dial delay.
 ;
 ; Value format is <flag>:<answered>:<billsec>:<lastseen>, one key rather than
 ; three so this costs a single lookup:
 ;   L  learning or learned  — evaluated against the thresholds below
 ;   P  pinned by an operator (didctl transfers add)  — always a transfer leg
 ;   S  suppressed by an operator (didctl transfers remove) — never one, and
 ;      never re-learned
 same => n,Set(SBC_XF=${DB(sbc/xfer/${SBC_EP}/${SBC_DEST})})
 same => n,GotoIf($["${SBC_XF}" = ""]?xfer_no)
 same => n,Set(SBC_XF_FLAG=${CUT(SBC_XF,:,1)})
 same => n,GotoIf($["${SBC_XF_FLAG}" = "S"]?xfer_no)
 same => n,GotoIf($["${SBC_XF_FLAG}" = "P"]?xfer_pinned)
 same => n,Set(SBC_XF_N=${CUT(SBC_XF,:,2)})
 same => n,Set(SBC_XF_B=${CUT(SBC_XF,:,3)})
 ; Both conditions, not either. Count alone flags any repeatedly-dialled
 ; prospect; duration alone flags a single long conversation.
 same => n,GotoIf($[${SBC_XF_N} < ${SBC_XFER_MIN_CALLS}]?xfer_no)
 same => n,GotoIf($[( ${SBC_XF_B} / ${SBC_XF_N} ) <= ${SBC_XFER_MIN_ACD}]?xfer_no)
 same => n,Set(SBC_XFER=transfer_leg_learned)
 same => n,Goto(xfer_yes)

 same => n(xfer_pinned),Set(SBC_XFER=transfer_leg_pinned)
 same => n,Goto(xfer_yes)
 same => n(xfer_tollfree),Set(SBC_XFER=transfer_leg_tollfree)

 ; --- this is a transfer leg ----------------------------------------------
 ; Do NOT touch CALLERID. The customer's value is already in it, and leaving
 ; it alone is what puts their number in From. P-Asserted-Identity and
 ; Remote-Party-ID are generated from the same CALLERID by res_pjsip, so all
 ; three carry it without a single assignment here.
 same => n(xfer_yes),GotoIf($["${SBC_CID_OK}" != "1"]?xfer_badcid)
 ; ANI feeds Remote-Party-ID and is not guaranteed to have been populated from
 ; From. Pin it explicitly so RPID cannot disagree with the other two.
 same => n,Set(CALLERID(ANI)=${CALLERID(num)})
 same => n,Set(CDR(did_selection_reason)=${SBC_XFER})
 same => n,Set(CDR(did_daily_count_at_selection)=)
 same => n,Log(NOTICE,SBC-TRANSFER-LEG callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} dst=${SBC_DEST} cid=${CALLERID(num)} rule=${SBC_XFER} note=customer-cid-passed-through-no-did-consumed)
 same => n,Goto(dial)

 ; The customer's caller ID is the whole point of a transfer leg, and this one
 ; is unusable — empty, alphabetic, wrong length or self-dialled. Asserting it
 ; risks a rejected INVITE or an unanswerable traceback with our name on it.
 ;
 ; So fall through to the normal rewrite. The buyer sees a pool DID, which is
 ; wrong but working; the alternative is a failed transfer with a live
 ; prospect on the line. Loud, because it means the customer's dialer is
 ; broken on the leg where caller ID matters most.
 same => n(xfer_badcid),Set(SBC_XFER=)
 same => n,Log(WARNING,SBC-TRANSFER-BADCID callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} dst=${SBC_DEST} custcid=${SBC_CID_RAW} note=transfer-leg-with-unusable-cid-falling-back-to-pool-did)

 ; ---- 8. DID selection and per-DID daily cap -----------------------------
 ; Runs AFTER the CPS and concurrency checks on purpose: a call that is about
 ; to be throttled must not consume a number's daily allowance first. Transfer
 ; legs never reach here at all — they consume no DID and no daily allowance.
 ;
 ; Counters are keyed by local date, so midnight rollover happens for free —
 ; there is no reset job that can fail and no race at the boundary. See
 ; [sbc-did] at the bottom of this file for the selection itself.
 same => n(xfer_no),Set(SBC_DID=)
 same => n,Set(SBC_DID_COUNT=)
 same => n,Set(SBC_DID_REASON=npa_match)
 same => n,Gosub(sbc-did,pick,1(${SBC_NPA},${GLOBAL(SBC_DID_POOL_${SBC_NPA})},${GLOBAL(SBC_DID_CNT_${SBC_NPA})}))
 same => n,GotoIf($["${SBC_DID}" != ""]?did_ok)

 ; Either this NPA has no pool of its own, or every DID in it is capped out
 ; for the day. Overflow obeys the same cap; there is no unmetered fallback
 ; anywhere in this path, and no single default number.
 same => n,Set(SBC_DID_REASON=overflow)
 same => n,Gosub(sbc-did,pick,1(OVERFLOW,${GLOBAL(SBC_DID_POOL_OVERFLOW)},${GLOBAL(SBC_DID_CNT_OVERFLOW)}))
 same => n,GotoIf($["${SBC_DID}" = ""]?rej_nodid)
 same => n,Log(WARNING,SBC-DID-OVERFLOW callid=${SBC_CALLID} dst_npa=${SBC_NPA} dst=${SBC_DEST} did=${SBC_DID} count=${SBC_DID_COUNT} cap=${SBC_DID_CAP} note=no-pool-or-pool-exhausted)

 ; ---- 8b. caller ID is SET here, and nowhere else ------------------------
 ; Validate our own selection before asserting it. A malformed DID reaching
 ; FracTEL is worse than a refused call: it is an unanswerable traceback with
 ; our name on it. This is the guard that makes a customer-supplied CID
 ; structurally unable to leave the box.
 same => n(did_ok),GotoIf($[${LEN(${SBC_DID})} != 11]?rej_didbad)
 same => n,GotoIf($["${SBC_DID:0:1}" != "1"]?rej_didbad)
 same => n,GotoIf($[${SBC_DID:1:1} < 2]?rej_didbad)
 same => n,GotoIf($[${SBC_DID:4:1} < 2]?rej_didbad)

 ; From comes from CALLERID(num). P-Asserted-Identity and Remote-Party-ID are
 ; generated from the same value by res_pjsip because the fractel endpoints
 ; set send_pai=yes, send_rpid=yes and trust_id_outbound=yes. Setting all
 ; three from one variable is what keeps them from ever disagreeing.
 same => n,Set(CALLERID(num)=${SBC_DID})
 same => n,Set(CALLERID(name)=${SBC_DID})
 ; ANI is carried separately in RPID and defaults to the original caller id
 ; if it is not overwritten. Leaving it alone would leak the customer's value
 ; into the very header this whole change exists to control.
 same => n,Set(CALLERID(ANI)=${SBC_DID})
 ; Read it back. If any of the above silently failed to take, refuse rather
 ; than dial with whatever is actually in there.
 same => n,GotoIf($["${CALLERID(num)}" != "${SBC_DID}"]?rej_didbad)
 same => n,GotoIf($["${CALLERID(ANI)}" != "${SBC_DID}"]?rej_didbad)

 same => n,Set(CDR(selected_did)=${SBC_DID})
 same => n,Set(CDR(did_selection_reason)=${SBC_DID_REASON})
 same => n,Set(CDR(did_daily_count_at_selection)=${SBC_DID_COUNT})

 ; ---- 9. dial FracTEL ----------------------------------------------------
 ; Round-robin across every gateway, one step per call. FracTEL's CPS limit
 ; is per receiving server, so even distribution is what yields the aggregate
 ; — stacking calls on gateway 1 caps the whole trunk at one server's limit.
 ;
 ; The rotor is an in-memory global incremented once per call: no lock, no
 ; disk write, and correct for any gateway count. On failure the ring is
 ; walked from wherever this call started.
 same => n(dial),Set(SBC_TRY=0)
 same => n,Set(SBC_GWROT=$[${IF($["${GLOBAL(SBC_GW_ROT)}" != ""]?${GLOBAL(SBC_GW_ROT)}:0)} + 1])
 same => n,Set(GLOBAL(SBC_GW_ROT)=${SBC_GWROT})
 same => n,Set(SBC_GWIDX=$[( ${SBC_GWROT} % ${SBC_GW_COUNT} ) + 1])

 same => n(gwloop),Set(SBC_GW=${GLOBAL(FRACTEL_GW_${SBC_GWIDX})})
 same => n,Set(CDR(fractel_gateway_used)=${SBC_GW})
 same => n,Log(NOTICE,SBC-DIAL callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} custcid=${SBC_CID_RAW} did=${SBC_DID} didreason=${SBC_DID_REASON} didcount=${SBC_DID_COUNT} xfer=${SBC_XFER} asserted=${CALLERID(num)} dst=${SBC_DEST} gw=${SBC_GW} attempt=${SBC_TRY} maxattempts=${SBC_MAX_ATTEMPTS})

 ; Clear app_dial's timing variables BEFORE dialling. On a second attempt the
 ; previous attempt's values are still sitting on this channel, and
 ; classifying attempt 2 with attempt 1's ring time would read a silent proxy
 ; failure as a consumer decline — the failure this whole block exists to
 ; avoid, arriving one attempt later. Empty is read as zero below, so a Dial()
 ; return path that never sets them degrades to "did not ring" rather than to
 ; stale data from the previous gateway.
 same => n,Set(RINGTIME_MS=)
 same => n,Set(DIALEDTIME_MS=)
 ; Our own attempt clock, because app_dial's is not usable here: DIALEDTIME_MS
 ; is populated only when the call is ANSWERED, so on every failure path it
 ; stays empty and SBC_DIAL_MS below read as zero. That silently disabled the
 ; fast-reject test at (declined) for the entire life of this dialplan --
 ; measured on this box, all 1,808 logged attempts carry dialed_ms=0.
 ; STRFTIME(,,%s%3q) is epoch milliseconds and is set on every path.
 same => n,Set(SBC_T0_MS=${STRFTIME(,,%s%3q)})
 ; The g option is what makes SBC-ATTEMPT observable on an answered call.
 ; Without it app_dial hangs the caller up the instant the callee does, none
 ; of the dialplan below runs, and every ANSWER is absent from the log --
 ; 1,808 attempts recorded against 2,182 real answers, so the Phase 2
 ; retroactive analysis could only ever see calls that failed.
 ;
 ; g changes logging, not routing: ANSWER is not CHANUNAVAIL, so it takes the
 ; same Goto(finish) it always did, two priorities later. Still no t/T (no
 ; transfer), no G, no M/L -- this leg connects two RTP streams and nothing
 ; else.
 same => n,Dial(PJSIP/${SBC_DEST}@${SBC_GW},${SBC_DIAL_TIMEOUT},g)
 same => n,Set(SBC_DS=${DIALSTATUS})
 ; Read immediately after Dial() returns, while HANGUPCAUSE still holds the
 ; cause from the channel just dialled. By the time the h extension runs it
 ; has been overwritten by this dialplan's own Hangup().
 same => n,Set(SBC_CAUSE=${HANGUPCAUSE})
 same => n,Set(SBC_RING_MS=${IF($["${RINGTIME_MS}" != ""]?${RINGTIME_MS}:0)})
 ; Measured, not reported: INVITE -> Dial() return, on every outcome. This is
 ; the value the fast-reject test at (declined) needs and never had.
 same => n,Set(SBC_DIAL_MS=$[${STRFTIME(,,%s%3q)} - ${SBC_T0_MS}])
 ; app_dial's own figure, kept alongside so the two can be compared on
 ; answered calls now that g makes them observable. Zero on failure paths.
 same => n,Set(SBC_ANSWERED_MS=${IF($["${DIALEDTIME_MS}" != ""]?${DIALEDTIME_MS}:0)})
 ; One line per INVITE. This is what lets Phase 2 separate a network reject
 ; from a human decline retroactively: cause=21 with ring_ms>0 is a person
 ; declining, cause=21 with ring_ms=0 in under a second is the trunk.
 same => n,Log(NOTICE,SBC-ATTEMPT callid=${SBC_CALLID} ep=${SBC_EP} dst=${SBC_DEST} gw=${SBC_GW} attempt=${SBC_TRY} status=${SBC_DS} cause=${SBC_CAUSE} ring_ms=${SBC_RING_MS} dialed_ms=${SBC_DIAL_MS} answered_ms=${SBC_ANSWERED_MS} billsec=${CDR(billsec)})

 ; ---- failover classification --------------------------------------------
 ; CONGESTION is a trunk-level failure — 503, and the transport-level failures
 ; that never produced a response at all. The call did not reach a consumer,
 ; so another proxy is worth one try.
 same => n,GotoIf($["${SBC_DS}" = "CONGESTION"]?gwnext)
 ; Anything that is neither CONGESTION nor CHANUNAVAIL is a real answer from
 ; the far end — ANSWER, BUSY (486/600), NOANSWER. Never retried. This is the
 ; original rule and it is unchanged.
 same => n,GotoIf($["${SBC_DS}" != "CHANUNAVAIL"]?finish)

 ; CHANUNAVAIL is ambiguous, and the ambiguity was doing real harm.
 ;
 ; 603 Decline maps to AST_CAUSE_CALL_REJECTED (21), and app_dial reports that
 ; as CHANUNAVAIL — the identical DIALSTATUS an unreachable proxy produces.
 ; chan_pjsip queues control frames only for 180, 183 and 200, so no 4xx or
 ; 6xx ever becomes AST_CONTROL_BUSY and the hangupcause path is the only one
 ; that runs. CHANUNAVAIL was already a failover condition, so every consumer
 ; who pressed decline was redialled across the remaining gateways — exactly
 ; the behaviour the comment here has always claimed to prevent.
 ;
 ; It is worse than merely useless: every gateway is a proxy on ONE
 ; subaccount reaching ONE upstream, so the rejection comes back identically
 ; from each of them. Measured on this box, 60% of the calls that failed over
 ; once went on to burn every remaining gateway.
 ;
 ; The discriminator is whether the call ever rang. A consumer can only
 ; decline a call that reached their handset, and reaching the handset means
 ; a 180 came back, which is what RINGTIME_MS records.
 same => n,GotoIf($[${SBC_RING_MS} > 0]?declined)
 ; Never rang, but took long enough that this is not a fast trunk-level
 ; refusal either. Ambiguous, so take the side that does not dial a consumer
 ; twice.
 ;
 ; SBC_FAST_REJECT_MS=0 disables this test, and 0 is the default. That is
 ; deliberate and it is NOT a no-op change: until SBC_DIAL_MS was measured
 ; above, it was always 0, this test could never fire, and every ambiguous
 ; CHANUNAVAIL fell through to (gwnext). Populating the clock would silently
 ; switch the branch on and start suppressing retries that production has
 ; been taking all along.
 ;
 ; Suppressing them is expensive. Reconciled against the carrier's own CDR for
 ; 2026-08-14, 1,153 of 3,145 calls retried and 434 of those retries ANSWERED
 ; -- 13.8% of all completed calls. Of first attempts that failed 603, 44.5%
 ; answered on the second gateway, which directly contradicts the "one
 ; subaccount behind every proxy, so the rejection comes back identically"
 ; reasoning above. Turn this on only after re-measuring that, on the lab box,
 ; against acceptance criteria 24-26.
 ; Two tests rather than one with '&': & is the channel separator in Dial()
 ; and its precedence inside $[ ] is not something to take on trust in the
 ; path that decides whether a consumer gets dialled twice. Disabled-check
 ; first, so the zero default short-circuits to exactly today's behaviour.
 same => n,GotoIf($[${SBC_FAST_REJECT_MS} <= 0]?gwnext)
 same => n,GotoIf($[${SBC_DIAL_MS} >= ${SBC_FAST_REJECT_MS}]?declined)
 same => n,Goto(gwnext)

 same => n(declined),Log(NOTICE,SBC-NO-RETRY callid=${SBC_CALLID} ep=${SBC_EP} dst=${SBC_DEST} gw=${SBC_GW} status=${SBC_DS} cause=${SBC_CAUSE} ring_ms=${SBC_RING_MS} dialed_ms=${SBC_DIAL_MS} note=far-end-rejected-this-call-not-retrying)
 same => n,Goto(finish)

 same => n(gwnext),Set(SBC_TRY=$[${SBC_TRY} + 1])
 same => n,Log(NOTICE,SBC-FAILOVER callid=${SBC_CALLID} gw=${SBC_GW} status=${SBC_DS} cause=${SBC_CAUSE} ring_ms=${SBC_RING_MS} attempt=${SBC_TRY})
 ; SBC_TRY is now the number of INVITEs already sent for this call, so this is
 ; a cap on INVITES PER CALL and not on gateways. Walking the whole ring was
 ; never the right behaviour: with one subaccount behind every proxy, attempt
 ; five returns what attempt one returned, while the carrier sees five times
 ; the CPS and a worse-looking traffic profile than the traffic actually is.
 ; render.sh has already clamped SBC_MAX_ATTEMPTS to the gateway count, so a
 ; single-gateway box cannot redial the same proxy here.
 same => n,GotoIf($[${SBC_TRY} >= ${SBC_MAX_ATTEMPTS}]?rej_exhausted)
 same => n,Set(SBC_GWIDX=$[( ${SBC_GWIDX} % ${SBC_GW_COUNT} ) + 1])
 same => n,Goto(gwloop)

 same => n(finish),Hangup()

 ; ---- rejection paths ----------------------------------------------------
 same => n(rej_killswitch),Set(SBC_REJ=KILLSWITCH)
 same => n,Goto(reject503)
 same => n(rej_dest),Set(SBC_REJ=NOT_NANP)
 same => n,Goto(reject503)
 same => n(rej_npa),Set(SBC_REJ=BLOCKED_NPA)
 same => n,Goto(reject503)
 same => n(rej_cps),Set(SBC_REJ=CPS_LIMIT)
 same => n,Goto(reject503)
 same => n(rej_cap),Set(SBC_REJ=CONCURRENCY_CAP)
 same => n,Goto(reject503)
 same => n(rej_exhausted),Set(SBC_REJ=ALL_GATEWAYS_FAILED)
 same => n,Goto(reject503)

 ; ---- high-cost prefix ---------------------------------------------------
 ; WARN, not NOTICE: this is money. The rate and label come straight from the
 ; rate deck row that matched, so the log line says what the call would have
 ; cost rather than merely that something was refused.
 same => n(rej_lrn),Set(CDR(reject_reason)=HIGH_COST_PREFIX)
 same => n,Log(WARNING,SBC-REJECT reason=HIGH_COST_PREFIX callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} custcid=${SBC_CID_RAW} dst=${SBC_DEST} prefix=${SBC_LRN_PREFIX} rate=${SBC_LRN_RATE} label=${SBC_LRN_DEST})
 same => n,Hangup(34)

 ; ---- no DID available ---------------------------------------------------
 ; Every DID in the destination NPA pool AND every DID in overflow is at its
 ; daily cap. ERROR, because this is the state that requires a human: either
 ; the pools are undersized for the traffic or something is looping.
 same => n(rej_nodid),Set(CDR(reject_reason)=NO_DID_AVAILABLE)
 same => n,Set(CDR(did_selection_reason)=none)
 same => n,Log(ERROR,SBC-REJECT reason=NO_DID_AVAILABLE callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} dst=${SBC_DEST} dst_npa=${SBC_NPA} cap=${SBC_DID_CAP} note=npa-pool-and-overflow-both-exhausted-until-local-midnight)
 same => n,Hangup(34)

 ; ---- our own DID is unusable --------------------------------------------
 ; Selection returned something that is not a valid 11-digit NANP number.
 ; That is a bug in dids.csv or in this dialplan, and the only safe response
 ; is to refuse: the alternative is asserting a malformed number, or falling
 ; back to the customer's CID, and this build exists to make the second one
 ; impossible.
 same => n(rej_didbad),Set(CDR(reject_reason)=BAD_SELECTED_DID)
 same => n,Log(ERROR,SBC-REJECT reason=BAD_SELECTED_DID callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} dst=${SBC_DEST} did=${SBC_DID} cidnum=${CALLERID(num)} note=refusing-rather-than-asserting-a-bad-number)
 same => n,Hangup(34)

 ; Bad caller ID gets 403, not 503. 503 says "try again later" and a dialer
 ; will do exactly that; 403 says "this call is wrong" and should make them
 ; fix their CID.
 ;
 ; Only reachable when SBC_VALIDATE_CID=true, which is NOT the default any
 ; more: the customer's CID is discarded on every call, so refusing traffic
 ; over it costs revenue and protects nothing. The WARNING at cid_verdict is
 ; the signal now. This path is kept because "reject their garbage outright"
 ; is still a legitimate operator choice.
 same => n(rej_cid),Set(CDR(reject_reason)=BAD_CALLERID)
 same => n,Log(NOTICE,SBC-REJECT reason=BAD_CALLERID callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} cid=${SBC_CID_RAW} dst=${SBC_DEST})
 same => n,Hangup(21)

 ; 34 = circuit congestion, which chan_pjsip maps to 503 Service Unavailable.
 same => n(reject503),Set(CDR(reject_reason)=${SBC_REJ})
 same => n,Log(NOTICE,SBC-REJECT reason=${SBC_REJ} callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} cid=${SBC_CID_RAW} dst=${SBC_DEST} concurrent=${SBC_CCNOW} cps=${SBC_CPSNOW})
 same => n,Hangup(34)


; --- teardown --------------------------------------------------------------
; cdr.conf sets endbeforehexten=no, so CDR() assignments made here still land
; in the written row. This is where hangup_cause gets recorded.
; SBC_CAUSE was captured the instant Dial() returned, while HANGUPCAUSE still
; held the dialled channel's cause. Prefer it: with the g option on Dial(),
; answered calls now reach (finish) and are torn down by this dialplan's own
; Hangup(), which overwrites HANGUPCAUSE before h runs. Calls that never got
; as far as Dial() -- every rejection path -- leave SBC_CAUSE empty and fall
; back to HANGUPCAUSE, which is what Hangup(21)/Hangup(34) just set.
exten => h,1,Set(CDR(hangup_cause)=${IF($["${SBC_CAUSE}" != ""]?${SBC_CAUSE}:${HANGUPCAUSE})})
 same => n,NoOp(SBC-END callid=${SBC_CALLID} src=${SBC_SRC_IP} ep=${SBC_EP} dst=${SBC_DEST} did=${SBC_DID} xfer=${SBC_XFER} disp=${CDR(disposition)} billsec=${CDR(billsec)} gw=${CDR(fractel_gateway_used)} reject=${CDR(reject_reason)})

 ; --- transfer-leg learning ------------------------------------------------
 ; EVERY counter write for rule 2 happens here and nowhere else. Detection in
 ; the call path is read-only, so no amount of learning can add post-dial
 ; delay. The channel is already being torn down; nothing is waiting on this.
 ;
 ; Per customer endpoint, not global: two customers dialling the same number
 ; are not evidence about each other, and one customer's traffic pattern must
 ; not silently change how another's caller ID is treated.
 same => n,GotoIf($["${SBC_XFER_ON}" != "true"]?hdone)
 same => n,GotoIf($["${CDR(disposition)}" != "ANSWERED"]?hdone)
 same => n,GotoIf($["${SBC_DEST}" = ""]?hdone)
 same => n,GotoIf($["${SBC_EP}" = ""]?hdone)
 same => n,Set(SBC_H_BS=${CDR(billsec)})
 same => n,GotoIf($[${SBC_H_BS} < 1]?hdone)

 same => n,Set(SBC_H_KEY=sbc/xfer/${SBC_EP}/${SBC_DEST})
 same => n,Set(SBC_H_CUR=${DB(${SBC_H_KEY})})
 same => n,GotoIf($["${SBC_H_CUR}" != ""]?h_have)

 ; Nothing stored yet. Only START tracking a destination once it has produced
 ; one answered call longer than the ACD threshold. Traffic reaches roughly
 ; 42,000 unique destinations a day and only about 80 ever produce a call over
 ; a minute — tracking the rest would add 20,000+ database writes a day for
 ; numbers that can never qualify.
 same => n,GotoIf($[${SBC_H_BS} <= ${SBC_XFER_MIN_ACD}]?hdone)
 same => n,Set(SBC_H_CUR=L:0:0:0)

 same => n(h_have),Set(SBC_H_FLAG=${CUT(SBC_H_CUR,:,1)})
 ; A destination an operator explicitly unpinned is never re-learned. Without
 ; this, `didctl transfers remove` would be undone by the next three calls.
 same => n,GotoIf($["${SBC_H_FLAG}" = "S"]?hdone)

 ; Read-modify-write, so it takes the same per-key lock discipline as the DID
 ; counters — but only one attempt. Two calls to the SAME destination ending
 ; in the same instant is rare, and losing that race costs one count, which
 ; delays learning by a single call. Retrying here would hold a channel open
 ; during teardown for no benefit.
 same => n,Set(SBC_H_LOCK=${TRYLOCK(xfer_${SBC_EP}_${SBC_DEST})})
 same => n,Set(SBC_H_N=$[${CUT(SBC_H_CUR,:,2)} + 1])
 same => n,Set(SBC_H_B=$[${CUT(SBC_H_CUR,:,3)} + ${SBC_H_BS}])
 ; lastseen is refreshed on every answered call, including for pinned and
 ; already-learned destinations, so an active buyer line never expires.
 same => n,Set(DB(${SBC_H_KEY})=${SBC_H_FLAG}:${SBC_H_N}:${SBC_H_B}:${STRFTIME(${EPOCH},,%Y%m%d)})
 same => n,ExecIf($["${SBC_H_LOCK}" = "1"]?Set(SBC_H_REL=${UNLOCK(xfer_${SBC_EP}_${SBC_DEST})}))
 same => n,NoOp(SBC-XFER-LEARN ep=${SBC_EP} dst=${SBC_DEST} flag=${SBC_H_FLAG} answered=${SBC_H_N} billsec=${SBC_H_B} acd=$[${SBC_H_B} / ${SBC_H_N}])

 same => n(hdone),NoOp(teardown complete)


; ===========================================================================
; [sbc-did] — DID selection with a per-DID daily cap.
;
; Gosub'd from [sbc-customer]. Not reachable from a channel: no endpoint has
; this as its context, and there is no include anywhere in this file.
;
;   Gosub(sbc-did,pick,1(<poolkey>,<pipe-delimited pool>,<count>))
;
; Sets, on return:
;   SBC_DID        the number to assert, or EMPTY if the whole pool is capped
;   SBC_DID_COUNT  that DID's call count for today INCLUDING this call, so a
;                  value equal to the cap means this was the last one
;
; --- Why it rotates the way it does ---------------------------------------
;
; The starting index comes from an in-memory rotor incremented once per call,
; per pool. That gives even distribution across the pool without a shared
; counter in the database and without a lock. Successive calls into the same
; NPA take successive numbers, so the DID chosen is always the one used
; longest ago — the least-recently-used discipline, obtained by construction
; rather than by writing a last-used timestamp for every DID on every call.
;
; It is deliberately not random. Random selection clusters: over a few hundred
; calls some numbers take three times the traffic of others, and traffic
; concentration on one number is exactly the pattern a carrier fraud system
; reacts to.
;
; It is also deliberately not derived from ${UNIQUEID}. See the note in
; [globals] — that sequence counts channels, not calls, and an even-sized pool
; would use only half its numbers.
;
; --- Why the lock is scoped to one DID ------------------------------------
;
; The cap is a check-then-increment, and without mutual exclusion two
; simultaneous calls can both read 199, both write 200, and both proceed —
; which is one call over the cap, silently. A single global lock would fix
; that and serialise every call on the box through one critical section; at
; 60 CPS that is a post-dial-delay risk and a single point of contention.
;
; So the lock name is the candidate DID. Two calls contend only when they are
; competing for the same number, which with rotation working is rare.
;
; On lock timeout the call PROCEEDS and logs WARNING. Undercounting one call
; against a 200/day safety limit is strictly better than dropping a billable
; call; the cap is a guard rail, not a billing boundary. That is a deliberate
; choice and it is the one place in this file where the failure mode is open
; rather than closed.
; ===========================================================================
[sbc-did]

exten => pick,1,Set(SBC_DID=)
 same => n,Set(SBC_DID_COUNT=)
 same => n,Set(SBC_P_KEY=${ARG1})
 same => n,Set(SBC_P_LIST=${ARG2})
 ; An NPA with no pool yields an empty count. Treat it as zero rather than
 ; letting an empty string reach $[] and throw an expression error.
 same => n,Set(SBC_P_CNT=${IF($["${ARG3}" != ""]?${ARG3}:0)})
 same => n,GotoIf($[${SBC_P_CNT} < 1]?ret)

 ; One step per call, per pool. Not persisted: rotation only has to spread
 ; load, and making it durable would put an sqlite write in every call path.
 same => n,Set(SBC_P_ROT=$[${IF($["${GLOBAL(SBC_ROT_${SBC_P_KEY})}" != ""]?${GLOBAL(SBC_ROT_${SBC_P_KEY})}:0)} + 1])
 same => n,Set(GLOBAL(SBC_ROT_${SBC_P_KEY})=${SBC_P_ROT})

 ; Walk the whole ring from the rotor position, taking the first DID under
 ; its cap. SBC_P_I is the number of candidates tried, so the loop visits
 ; every number exactly once before giving up.
 same => n,Set(SBC_P_I=0)
 same => n(loop),Set(SBC_P_IDX=$[( ( ${SBC_P_ROT} + ${SBC_P_I} ) % ${SBC_P_CNT} ) + 1])
 same => n,Set(SBC_P_CAND=${CUT(SBC_P_LIST,|,${SBC_P_IDX})})

 ; --- critical section, scoped to this one DID ---------------------------
 same => n,Set(SBC_P_TRIES=0)
 same => n,Set(SBC_P_LOCK=${TRYLOCK(did_${SBC_P_CAND})})
 same => n(relock),GotoIf($["${SBC_P_LOCK}" = "1"]?locked)
 same => n,Set(SBC_P_TRIES=$[${SBC_P_TRIES} + 1])
 same => n,GotoIf($[${SBC_P_TRIES} > 3]?nolock)
 same => n,Wait(0.05)
 same => n,Set(SBC_P_LOCK=${TRYLOCK(did_${SBC_P_CAND})})
 same => n,Goto(relock)

 ; ~150ms of contention on one number. Take the call, count it best-effort,
 ; and make sure somebody sees this in the log.
 same => n(nolock),Log(WARNING,SBC-DID-LOCK-TIMEOUT did=${SBC_P_CAND} note=proceeding-unlocked-this-call-may-undercount)

 same => n(locked),Set(SBC_P_USED=${IF($["${DB(sbc/didcnt/${SBC_DAY}/${SBC_P_CAND})}" != ""]?${DB(sbc/didcnt/${SBC_DAY}/${SBC_P_CAND})}:0)})
 same => n,GotoIf($[${SBC_P_USED} >= ${SBC_DID_CAP}]?capped)
 same => n,Set(DB(sbc/didcnt/${SBC_DAY}/${SBC_P_CAND})=$[${SBC_P_USED} + 1])
 same => n,ExecIf($["${SBC_P_LOCK}" = "1"]?Set(SBC_P_REL=${UNLOCK(did_${SBC_P_CAND})}))
 same => n,Set(SBC_DID=${SBC_P_CAND})
 same => n,Set(SBC_DID_COUNT=$[${SBC_P_USED} + 1])
 same => n,Goto(ret)

 ; This number is done for the day. Release before trying the next one —
 ; holding a lock while taking another is the only way this could deadlock.
 same => n(capped),ExecIf($["${SBC_P_LOCK}" = "1"]?Set(SBC_P_REL=${UNLOCK(did_${SBC_P_CAND})}))
 same => n,Set(SBC_P_I=$[${SBC_P_I} + 1])
 same => n,GotoIf($[${SBC_P_I} < ${SBC_P_CNT}]?loop)

 ; Fell off the end: every DID in this pool is at its cap. Returning with
 ; SBC_DID empty is what sends the caller to overflow, or to a 503.
 same => n(ret),Return()


; ===========================================================================
; [sbc-lrn-blocklist] — generated from blocklist.csv by render.sh.
;
; One extension per high-cost prefix. Gosub'd from [sbc-customer] and guarded
; by DIALPLAN_EXISTS, so on the common miss nothing in here runs at all.
;
; Asterisk's extension matcher already prefers the most specific pattern, so
; longest-prefix-wins is free: with both _1268. and _1268555010 present, a
; call to 12685550101 matches the longer one and reports the narrower rate.
;
; @@LRN_COUNT@@ prefix(es) loaded. Regenerate after every rate deck update:
;   python3 tools/build-blocklist.py --deck <ShortDuration.csv>
;
; LIMITATION: the deck is LRN-rated, meaning the charge follows where a number
; has been ported to. This box performs no LNP dip and has no LRN at call
; time, so it matches the number DIALLED. Numbers natively in an expensive
; prefix are caught; numbers ported into one are not. Partial cost control,
; not complete. The CDR carries an lrn column so prefixes found in FracTEL's
; rated CDR after the fact can be added here.
; ===========================================================================
[sbc-lrn-blocklist]

; Sentinel, so this context is never empty even with an empty blocklist. No
; destination reaching the guard above is anything but 11 digits, so nothing
; can match it.
exten => none,1,Return()

@@INCLUDE:lrn_blocklist@@
