; ===========================================================================
; modules.conf — rendered by render.sh from @@RENDERED_FROM@@.
;
; autoload=yes with an explicit denylist, rather than autoload=no with an
; allowlist. That is a deliberate trade and worth understanding:
;
;   An allowlist is the stronger posture, but it is also the one that breaks
;   the box at 3am because a transitive dependency was missed, and a broken
;   SBC on test day is worse than a slightly larger module surface. The
;   denylist below closes every path the threat model actually cares about —
;   command execution, remote control APIs, and alternate channel drivers —
;   while nothing loaded here is reachable from the network anyway, because
;   the firewall exposes only 5060 and the RTP range to four addresses.
;
;   Moving to a curated allowlist is the right hardening follow-up once the
;   deal closes and there is time to test a full startup.
;
; The list is generated by render.sh and contains ONLY modules that actually
; exist in /usr/lib/asterisk/modules on this host. A noload for a module that
; was never built is harmless, but it muddies the "zero warnings on load"
; check in acceptance criterion 2.
;
; Note on Local channels: Local/ is compiled into the Asterisk core in 20 and
; cannot be unloaded. It is unreachable from customer traffic by construction
; — [sbc-customer] never uses it and has no context includes.
; ===========================================================================

[modules]
autoload=yes

@@INCLUDE:noload@@

; --- what this box actually depends on -------------------------------------
; Documented as comments, NOT as `load =>` lines. With autoload=yes an
; explicit load line is functionally redundant, and if any name here were
; wrong or packaged differently on this distro it would produce a load
; warning — which would fail the zero-warnings acceptance check for no gain.
; This list is here so a future switch to autoload=no starts from something
; real.
;
;   res_pjsip.so                        res_pjsip_session.so
;   res_pjsip_acl.so                    res_pjsip_endpoint_identifier_ip.so
;   res_pjsip_authenticator_digest.so   chan_pjsip.so
;   res_rtp_asterisk.so                 app_dial.so
;   pbx_config.so                       app_verbose.so      (Log)
;   func_channel.so                     func_groupcount.so  (GROUP/GROUP_COUNT)
;   func_strings.so                     func_cut.so         (FILTER/CUT/LEN)
;   func_logic.so                       func_math.so
;   func_callerid.so                    func_cdr.so
;   cdr_custom.so                       cdr_csv.so
;   codec_ulaw.so                       codec_alaw.so
;   format_pcm.so                       res_security_log.so
;
; res_pjsip_authenticator_digest is deliberately NOT in the denylist above,
; even though nothing here uses digest auth. With no authenticator
; registered, res_pjsip logs "No SIP authenticator registered. Trusting SIP
; requests without authentication" and lets unidentified requests through to
; the artificial endpoint. Keeping it loaded is precisely what makes an
; unmatched source get challenged and then refused rather than trusted.
; Removing it would look like hardening and would open the box up.
